### ISSUE TITLE
Swift: Try to resolve power supply input faults at startup

### ISSUE THREAD

**Issue by spinler** [ibm-openbmc/dev#1025]

**Comment by bjwyman** [comment]
If the power is pulled from a power supply, an input fault will get logged by the psu-monitor code.

When an input power fault gets logged, it has a call out, which should drive the LED to the faulted state, turning the power supply amber LED on.

The logs are persisted.

If pulling the power from the power supply results in the BMC going down, when the BMC comes back up, after the power is re-applied to the power supply/supplies, the persisted log for the fault can result in the LEDs being set back to the faulted stated due to the call out in the log, even though the input fault was resolved prior to the psu-monitor application starting.

Normally, such as when there are two power supplies holding up the BMC, if an input fault is detected, then the power is re-applied, the error logged for the input fault would get marked as resolved automatically by the psu-monitor code.

If the input fault is resolved prior to the psu-monitor code running, this automatic marking of the fault being resolved is not occurring, resulting in power supplies with amber fault LEDs being on when no fault (potentially) is present.

**Comment by bjwyman** [comment]
analyze() -> checkInputFault()
https://github.com/openbmc/witherspoon-pfault-analysis/blob/5c0ce175116cb15d0601b81202e4fcb176d042d4/power-supply/power_supply.cpp#L141

checkInputFault() -> resolveError()
https://github.com/openbmc/witherspoon-pfault-analysis/blob/5c0ce175116cb15d0601b81202e4fcb176d042d4/power-supply/power_supply.cpp#L299

Some path change round about there.

**Comment by spinler** [comment]
this is done

**Comment by bjwyman** [comment]
https://github.com/openbmc/witherspoon-pfault-analysis/commit/817f8a7a82983d3e7bdc409ca86f2897540e400f
