### ISSUE TITLE
Implement PLDM responder to store a PEL

### ISSUE THREAD

**Issue by dkodihal** [ibm-openbmc/dev#1062]
- [ ] Implement routing based on PLDM file type
- [ ] Invoke API to store PEL

Needs to be broken down to crisper tasks.

**Comment by sampmisr** [comment]
1. write responder handler for "WriteFileByTypeFromMemory" in file_io.cpp

2. doubt -  will the file handle be always 0xFFFFFFFF here? or we should design for a valid handle as well? in that case i believe updateFileTable" is required

3. design a generalised framework to handle any type of file which will be added in future viz dump/lid (apart from pel files) in the file_io.cpp

4.  for a single file (be it pel/dump/lid) the "WriteFileByTypeFromMemory" command will be received only once. is that assumption correct? but if we get "WriteFileByTypeFromMemory" twice then somehow we need to conclude that this "WriteFileByTypeFromMemory" command is a continuation of the previous one or it is a new one altogether. this situation can arise while transferring multiple lids. we need to know when one lid is ending and next one is starting. 


5. check for the file type. create separate handlers/files for each file type. this will be done after checking the file type in file_io.cpp

6. rewrite the transferAll() api to actually transfer the content. this should be a new common code which will be used by all file types. currently transferAll() uses fs::path to mention the location of the file to write to. now this will be an in memory structure as of now/or a shm object?

7. call the pel daemon dbus/api to transfer the pel content to be committed. pels will be transferred in a single dma transfer since pel maxsize is way less than dma max size

8. send the response back to host only after the pel content is successfully transferred to pel daemon

**Comment by dkodihal** [comment]
Resolved by https://gerrit.openbmc-project.xyz/#/c/openbmc/pldm/+/24636/
