### ISSUE TITLE
Pick up the Rainier MRW

### ISSUE THREAD

**Issue by geissonator** [ibm-openbmc/dev#1113]
Point recipe to correct MRW and do some basic validation of the generated data.

**Comment by santoshpuranik** [comment]
The Rainier XML is missing a few things that breaks the IPMI parsers. Since we are still unsure what IPMI sensors we'll ultimately need for Rainier and also the fact that the number of sensors currently in the MRW (> 500) cannot all be assigned a unique IPMI sensor ID (limited to 255 in standard IPMI).

So, the current plan to pull in the MRW into the Rainier builds is to:
* Define the attributes for a bare minimum of IPMI sensors in the Rainier MRW. I have asked Ruby to do so in the Rainier PR: https://github.ibm.com/openbmc/rainier-xml/pull/2
* Push changes to the IPMI MRW parsers to skip and incomplete MRW sensor/FRU targets and not break compilation. The scripts have been modified to take in an extra option to enable this. The changes are here: https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-mrw-tools/+/26039
* Change the recipes to enable the skip-broken-mrw option for Rainier alone. These changes are here: https://gerrit.openbmc-project.xyz/c/openbmc/meta-phosphor/+/26038, https://gerrit.openbmc-project.xyz/c/openbmc/meta-ibm/+/26037

Once the above changes are merged, we can update the MRW SRC URI in rainier.conf to point to the Rainier XML.

**Comment by santoshpuranik** [comment]
Everything is merged to master. Closing this one.
