### ISSUE TITLE
eBMC GUI: Service Login

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#1193]
## Stakeholders
**SME**: @ratagupt, @joseph-reynolds 
**Design Researcher**:
**UX Designer**:
**FED**:

## Summary 
- 

## Use Case
As a Service Rep, I need access to information and functions that customers should not have access to.

## FED
Several mockups included parts for CE login. This list is to verify what is missing in the UI for CE login:

- [ ] Local user management privileges update https://github.com/ibm-openbmc/dev/issues/2550
- [ ] Overview, service login https://github.com/ibm-openbmc/dev/issues/3393
- [ ] Key Clear #2102 
- [ ] ACF upload #3019 
- [ ] Dumps #3005 

## References/Resources
- [Discovery folder](https://ibm.box.com/s/l22hg6py8x1djzdz30lritnrhxzyscbk)
- Slack channel: #openbmc-celogin
- [Service login infrastructure](https://app.mural.co/invitation/mural/dept3als0833/1597162923789?sender=josephreynolds12415&key=3e32322e-b7fa-4f86-afd5-a5fff3886280) (Mural)

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by nicoleconser** [comment]
View [Overview of Service Login infrastructure](https://app.mural.co/invitation/mural/dept3als0833/1597162923789?sender=josephreynolds12415&key=3e32322e-b7fa-4f86-afd5-a5fff3886280) on Joseph's Mural

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by joseph-reynolds** [comment]
As explained in (internal IBM) SW543421, BMC admins have very limited privileges to control the special built-in BMC "service" user account.  Why?  Because that user has the OemIBMServiceAgent role which has Restricted=true.

For details see Redfish spec 1.12.0 (http://redfish.dmtf.org/schemas/DSP0266_1.12.0.pdf) subsection "Restricted roles and restricted privileges" (excerpted here):
> Services shall not allow:
> - A RoleId value for a restricted role to be specified when creating or modifying a ManagerAccount resource. This ensures administrators cannot create an account for themselves that has a restricted role.
> - Modification of ManagerAccount resources with a RoleId property containing a value for a restricted role, with the exception of the Enabled property. This ensures administrators cannot gain access to another account.
> - Deletion of ManagerAccount resources with a RoleId property containing a value for a restricted role.


Here are my ideas for affected Web GUI functions:

1. Add user.  Do not allow the OemIBMServiceAgent role to be selected.  Why?  That role is restricted.
2. Modify user.  Do not allow any user to change to the OemIBMServiceAgent role.  Why?  That role is restricted.
3. Modify user.  Restrict how the special "service" user account can be modified.  Why?  The "service" account has a restricted role.  Details:
   - The functions to delete the user, rename the user, change the user's role, change the user's password are not allowed.
   - The functions to reset the user's locked password and to enable/disable the account are allowed.  (The usual privileges apply, meaning only a BMC admin user is allowed to do these.)
   - The special function to upload an ACF, show ACF details, and to delete the ACF are allowed (by an admin user).

Also the "role-to-privilege" table should:
- Have a new column for the OemIBMServiceAgent role.
- Have a new row for the new OemIBMPerformService privilege.  Or you could omit this if it is confusing to end users.
- You could get these from the assigned privileges available via URI /redfish/v1/AccountService/Roles/OemIBMServiceAgent.  But realistically they are hard-coded and will not change.

Also as mentioned before, the name OemIBMServiceAgent may be confusing to end users, so we may want the Web app to translate it to IBMServiceAgent or ServiceAgent for use on the GUI.  (But note the Redfish interface only knows the OemIBMServiceAgent value.)


Low-level design notes:

In some ideal world, we would implement the "Restricted" role in a general way: enhance the Web GUI to retrieve the Role information from URI /redfish/v1/AccountService/Roles/OemIBMServiceAgent and determine if the Restricted=true property is used.  Then use that information to inform the operations above (add user, modify user, etc.) if the should be offered to the GUI user. 

If you want to cheat, you can program the Web app to know OemIBMServiceAgent has Restricted=true, and to know the service account uses a role which has Restricted=true.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh
