### ISSUE TITLE
phosphor-regulators: Stop using scripts to modify regulator configuration on Rainier

### ISSUE THREAD

**Issue by smccarney** [ibm-openbmc/dev#1317]
On Witherspoon several scripts are currently used to configure voltage regulators:
* vrm-control.sh
* power-workarounds.sh

There are also service files that unbind/bind regulator device drivers and call these scripts.

On Rainier the phosphor-regulators application will take the place of these scripts.  As a result, the scripts should not be called or included in the firmware image.  If a script is updating other devices as well, such as the power-sequencer, then the regulator portions of the script should be removed.

**Comment by msbarth** [comment]
With the removal of Rainier from the `ibm-ac-server` machine type these scripts are no longer installed within the Rainier image. The same goes for the regulator unbind/bind script.

The service files associated with these scripts are also not installed into the Rainier image due to no longer being considered an `ibm-ac-server`. There was a window of time where Rainier was included as an `ibm-ac-server`, which would correlate to the need for this issue to be addressed, but I'm not seeing any of what's referenced being installed and/or run within the latest Rainier image I ran within sim.

**Comment by msbarth** [comment]
None of these referenced exist on Rainier, closing.
