### ISSUE TITLE
GUI : Design : Add route transition

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#1645]
## Overview
We need a transition that keeps the screen from jumping or continuously changing as data is populated. Our current design uses a large spinner. Another idea is a skeleton screen that is shown until all data is loaded.

## Considerations
- [x] Spinner is not modern
- [x] Layout no longer causes jumping due to default values
- [x] Data loads async and need a way to show users that data is loading without disrupting the entire experience
- [x] If solutions are too time intensive, use existing spinner and create a story for updating
- [ ] Assure cross-browser consistency (spinner intermittently not working in firefox)

## Resources
* https://router.vuejs.org/guide/advanced/transitions.html#per-route-transition

**Comment by yoshiemuranaka** [comment]
Will add page loading indication page by page in separate commits since it will require unique store/api request modifications

- [ ] Loading bar component 
  - https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/31743
- [ ] Overview page
- [ ] Sensors page
- [ ] Server power operations page
- [ ] LDAP page
- [ ] Local user management page
- [ ] SSL certificates page
  - https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/31744/1
