### ISSUE TITLE
Log errors above ambient performance loss limit

### ISSUE THREAD

**Issue by derekhoward55** [ibm-openbmc/dev#1696]
Log error when go above perf loss ambient temperature limit (35C).  Log info error when temp drops back below the reset limit (32C for hysteresis). 

Limits should be data-driven, same location as epow/warning limits.

Inform OCC when in this environment so they don't log their own error for taking away performance/power if needed.

**Comment by spinler** [comment]
@derekhoward55 Can we have the OCC just get this temp from the MRW, and then they also log the error since they are the ones lowering performance?

**Comment by derekhoward55** [comment]
that is another option.  previously we did it from the sp since the sp logged all the other ambient temp errors (eg for epows).  @marthabroyles thoughts? does the OCC get ambient sent to it today, and any other mrw settings?

**Comment by marthabroyles** [comment]
OCC currently does not receive ambient.  We also had the SP do this logging because the environment window for performance loss could also be due to fan failure so moving to OCC to log this would also involve the OCC knowing about fan fails which I don't want to add in OCC.

**Comment by spinler** [comment]
Code is in place to log xyz.openbmc_project.Sensor.Threshold.Error.TemperaturePerfLossHigh PEL if that threshold is exceeded.  I did not put that threshold on the virtual ambient yet because there wasn't a value for it in the workbook.

openpower-occ-control can probably also just watch this alarm property if it wants to know about the high ambient.

**Comment by derekhoward55** [comment]
This is no longer a requirement.
