### ISSUE TITLE
PFP::sensor-monitor - Altitude error logging (system power on)

### ISSUE THREAD

**Issue by derekhoward55** [ibm-openbmc/dev#1697]
Thermal team cares about pressure, not necessarily altitude, for fan control.  Needs to be converted to altitude for fan control to meet up with ASHRAE requirements.  Determine if alt or pressure should be in config data.

Log "outside environment" error if system is above altitude limit during the power on (above 3050m in sys workbooks).

No performance loss ambient nor altitude/pressure support needed.

Limits should be data-driven, same location as ambient epow/warning limits.

**Comment by spinler** [comment]
The altitude is already exposed as a virtual sensor and has the warning threshold of 3050: https://github.ibm.com/openbmc/openbmc/blob/1020/meta-ibm/recipes-phosphor/sensors/phosphor-virtual-sensor/p10bmc/virtual_sensor_config.json#L38

The sensor-monitor code (https://github.com/openbmc/phosphor-fan-presence/tree/master/docs/sensor-monitor) watches for the Warning alarm, and will create an event log (and on our systems an IBM PEL).  That PEL needs to call out an ALTITUDE symbolic FRU.

The remaining work is just:
1.  Verify an event log is created for an altitude over 3050m.  If dbus-sensors is compiled with -Dinsecure-sensor-override=enabled, then one can do a busctl set-property on the pressure sensor with a value to produce an altitude that high.
 - If I did the sensor-monitor code right, that event should be xyz.openbmc_project.Sensor.Threshold.Error.AltitudeWarningHigh
 - Can look at d-bus event logs with obmcutil listlogs and obmcutil showlog
2. A PEL message registry entry needs to be made to convert that event log into a proper PEL with a unique SRC.  It would be similar to the temperature warning one https://github.com/openbmc/phosphor-logging/blob/master/extensions/openpower-pels/registry/message_registry.json#L1962.
 - An SRC of 0x280A could be used.
 - Subsystem: ext_env
 - A new symbolic FRU for ALTITUDE is needed.  (The symoblicFRUs map in pel_values.cpp in phosphor-logging would need an update, along with the schema)
 - There is more info on the registry and testing at https://github.com/openbmc/phosphor-logging/tree/master/extensions/openpower-pels/registry#modifying-and-testing
 - One can look at pels with the peltool command (-l and -i)
3.  Also an AltitudeWarningHighClear PEL registry entry is needed for when the threshold de-asserts, in case that happens since the sensor-monitor will do that automatically.  It is informational so doesn't need a callout.  SRC would be 0x280B.

**Comment by RashmicaG** [comment]
Tested and merged.
