### ISSUE TITLE
PFP::control - Integrate Vdd VRM temp in fan control loop

### ISSUE THREAD

**Issue by derekhoward55** [ibm-openbmc/dev#1698]
Vdd VRM temp is the only VRMs temp needed for fan control per thermal engineers. Already read via i2c and part of fan control for earlier systems, use same support for Rainier but dependent on refactored vrm support. 

OCC also reads Vdd vrm temp over AVSbus and returns to BMC in poll response. BMC ignores this, but can use in future if need be.  A future improvement would be to use this temp instead, as 1) it is what the OCC uses for it's dvfs decisions and 2) in mfg/characterization, the vrm service will temporarily to turned off (<1s?) so Vdd temp would not be read. using the reads from the OCC would close this window.  If this is to be implemented, open this work in another issue.

**Comment by msbarth** [comment]
@derekhoward55 FWIW, since all the OCC sensors to dbus is being re-worked into the openpower-occ-control app, they could likely easily include the VDD temp from the OCC out on dbus, which fan control could easily read it from there instead of the phosphor-regulators app. As long as the OCC device driver is providing the VDD in the poll response up to the openpower-occ-control, that could then just translate to dbus then.

The initial issue was (not knowing if the OCC device driver is supplying the VDD temp) was also in the phosphor-hwmon app not supporting getting this temp.

**Comment by msbarth** [comment]
Duplicate of https://github.com/ibm-openbmc/dev/issues/2753 ?

**Comment by cjcain** [comment]
Vdd temp is provided in the OCC poll response, so the sensor will be available on dbus.

**Comment by msbarth** [comment]
@cjcain Not necessarily, the OCC device driver would roll it up to sysfs on the BMC, then the openpower-occ-control app would need to consume it from there and then serve the sensor onto dbus. I dont believe it was asked in the work being done to start provided the OCC temps by the openpower-occ-control app to include the VDD in those sensors it will put on dbus.

**Comment by cjcain** [comment]
I agree, that they may not be the ones doing it, but it will still need to get done (by me if no one else)

**Comment by derekhoward55** [comment]
Closing this as dup of https://github.com/ibm-openbmc/dev/issues/2753.
