### ISSUE TITLE
GUI : Design : Research - Importance of last power operation / last restart information

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#1732]
## SMEs
**BMC**: @gtmills 

## Problem
The `Last Power Operation` information displayed on the Server Power Operations page and the `Last Restart` information displayed on the Reboot BMC page are not supported by the Redfish API. 

## Goal
Determine the value of of this information to our design partners. There are many API change requests being proposed to the Redfish community. We need to know how important this information is.

## References & Resources
**Feature discovery:** https://ibm.box.com/s/zmgr05a65kntlamw34048801ryane3t9

## Research document
https://app.mural.co/t/ibmpower1831/m/ibmpower1831/1579876154638/461f54138802390d766c56175c60c353a391e402

**Comment by ryanarnell** [comment]
**User 1  Yes Important**
I think" for IBM Power10 OpenBMC will be the new standard in place of the F.S.P I would say this information is useful/helpful.  I say this cuz for a PowerVM Power10 host it is useful information to see the "uptime" of the "managed frame" and BMC.  On a PowerVM host the uptime will be independent of the OS's uptime since they can be different.  On a OPAL/NON-PowerVM the uptime should be the same as the OS's uptime.

**Comment by ryanarnell** [comment]
**User 2: Somewhat important** 
If unexpected power failure happens when they are away, they will know when it happens. Also can get it from event logs. 

Will use this to calculate up times

**Comment by derick-montague** [comment]
Is there an understanding about OS vs chasis uptime?

**Comment by derick-montague** [comment]
This was available in ASMI. Need to set up time with @geissonator or set up time in SoS overflow to discuss.

**Comment by nicoleconser** [comment]
Gunnar and I spoke with @geissonator today; it was decided that @gtmills will submit a Redfish proposal for "Time of Last Power Operation" of the **_system_**, but not of the firmware (currently both are displayed in ASMI).
