### ISSUE TITLE
Fan hot-swap vpd update and phyp notification

### ISSUE THREAD

**Issue by derekhoward55** [ibm-openbmc/dev#1774]
Verify hot-swapped fan speeds up correctly without bringing system down, and VPD gets updated appropriately. 

Send alert to PHYP when removed, and after VPD has been updated when installed.

**Comment by msbarth** [comment]
@derekhoward55 This is being entirely handled by the vpd app now correct?

**Comment by derekhoward55** [comment]
@msbarth the vpd app will fill in the hardcoded vpd (https://github.com/ibm-openbmc/dev/issues/1592).  I'd still like us to do a fan hot-swap on real hardware when all the code is in place to make sure the fan control and full path up to phyp works.

**Comment by msbarth** [comment]
@derekhoward55 Ok, wouldnt we think that the vpd app should verify this path since they own all the code interfacing with the hypervisor and dealing with fan vpd? I'd like to see us dis-associate from the dev and test if we dont own any of the code that deals with fan vpd anymore.

Hot-swapping a fan and verifying fan control reacts appropriately would still be owned by me, which I'll verify.

**Comment by msbarth** [comment]
- Verified hot-swapped fan speeds up correctly without bringing system down.
- Synthesized VPD for Rainier fans added/populated on fan inventory objects
- Everest VPD populated on fan inventory objects

As noted, VPD to PHYP path to be verified by VPD team
