### ISSUE TITLE
CElogin APIs

### ISSUE THREAD

**Issue by gtmills** [ibm-openbmc/dev#1830]
This is a placeholder for the APIs needed for the BMC admin to upload and delete **Access Control Files ([ACFs](https://github.com/ibm-openbmc/dev/issues/2562))** which allow the service user to authenticate.

Three APIs are planned:
- POSTing a valid ACF allows the service user to authenticate using the password associated with that ACF.
- DELETEing the ACF removes the service users ability to authenticate.
- GETting the ACF shows basic information.

TODO: It is not yet decided if these are Redfish or REST APIs, and the URI has not yet been chosen.

See also the GUI pieces for this here https://github.com/ibm-openbmc/dev/issues/1193

**Comment by joseph-reynolds** [comment]
Here is a design sketch of the new Redfish APIs needed so that BMC admin can enable service logins.  (Please note intended only to cover the REST APIs, not to answer all questions about the design.)  Note IBM POWER server service agents were formerly known as Customer Engineers (CEs) and now called service and support representatives (SSRs).  For OpenBMC based systems, we'll use the special "service" account for this purpose.

Here is a scenario sketch when service is needed on a customer system:
The service agent obtains a certificate + password from the organization (such as IBM).  The certificate is given to the BMC admin who uploads it to the BMC.  When this certificate is valid, it enables the service agent to authenticate using the password associated with the certificate.

There are many more details, but the main ideas for the new APIs for URI `/redfish/v1/AccountService/Accounts/service/Certificates` are:
 - POST - upload a certificate that enables the service agent's login password
 - DELETE - delete the certificate that enables the service agent's login password
 - GET - show details about the cert: if the service agent can login, and for what time period

This design is similar to the GLOME alternative presented in the 2020-08-19 meeting of the OpenBMC security working group - https://docs.google.com/document/d/1b7x9BaxsfcukQDqbvZsU2ehMq4xoJRQvLxxsDUWmAOI 

A Linux-PAM authentication module is needed to validate the “service” account password with the hashed copy stored in the uploaded certificate.  Its logic would be something like this:
1. If the user account != “service” then exit to the next module.
2. Ask the user for the password and hash it.
3. If the BMC has a valid unexpired service account certificate, then check if  ((the entered password hash) == (the password hash stored in the cert)).
   - Then: Approve or deny the request based on the results.
   - Else: Deny the request.

**Comment by joseph-reynolds** [comment]
Moved the Linux-PAM auth modules into new story #2562.

**Comment by joseph-reynolds** [comment]
Do we need a way for the service agent to upload the ACF without the cooperation of the admin by asserting physical presence?

**Comment by ojayanth** [comment]
@gtmills moving back to gunnar to assign to the correct owner.

**Comment by gtmills** [comment]
@joseph-reynolds Should you own this? @mzipse FYI

**Comment by joseph-reynolds** [comment]
Here are some more ideas for the REST APIs which work with ACFs:

**POST** - upload an ACF certificate which enables the service agent's login password
At most one ACF may be present.
Uploading a valid ACF shall replace any existing certificate.  A failed ACF upload shall not affect any existing ACF.
Uploading an ACF shall fail for the following reasons, and the reason shall be communicated to the API user:
- Invalid ACF format.
- Invalid signature.
- Invalid serial number.
- ACF already expired.

**DELETE** - delete the ACF certificate

**GET** - show details about the ACF certificate. Show if the cert is present and when it expires

**Comment by gtmills** [comment]
@joseph-reynolds Can we close this?

**Comment by rfrandse** [comment]
tracking in jira
