### ISSUE TITLE
Enable base full-function fan support

### ISSUE THREAD

**Issue by derekhoward55** [ibm-openbmc/dev#1869]
Turn off the default to high speed when we are able to read the necessary component temp sensors.

Thermal alg: 3-zone (like in P9) is plan of record.  Support same obmc fan control and monitoring.  Updates for enterprise, including fail&presence info, error logging and shutdown (service mode & meltdown), thermal sensor info, trip points, etc in later story (https://github.com/ibm-openbmc/dev/issues/1773).

Use same MAX31785 (rev A) fan controller as before. 

Ping watchdog timer.

**Comment by msbarth** [comment]
- [x] Turn off the default to high speed when we are able to read the necessary component temp sensors.
**Dynamic fan control will occur once the events configuration is populated to being changing fan speeds.**

- [x] Thermal alg: 3-zone (like in P9) is plan of record. Support same obmc fan control and monitoring. Updates for enterprise, including fail&presence info, error logging and shutdown (service mode & meltdown), thermal sensor info, trip points, etc in later story (#1773).

- [x] Use same MAX31785 (rev A) fan controller as before.

- [x] Ping watchdog timer.

I dont see any need to keep this story open since these items have been already completed or covered under other story(s)
