### ISSUE TITLE
Guard: API- Guard partition write

### ISSUE THREAD

**Issue by ojayanth** [ibm-openbmc/dev#1955]
- Write GUARD information to Guard partition.

**Comment by devenrao** [comment]
1. Block level write methods to read guard records from the guard partitoin.
2. Find the last position of the record to write and then write bytes for the size of the guard recrod 
3. If ecc protection is enabled, ecc bytes need to be read and validation need to be performed.
4. Throw runtime errors so that the caller can catch and create PEL's
5. Do not use phosphor-logging traces as there will be cyclic dependency as the guard manager will be implemented in phosphor-logging , rather use normal std::cerr for any log statements.

Code to refer from skiboot for guard read
block_level_read (https://github.com/open-power/skiboot/blob/master/libflash/blocklevel.c#L103)
Flash File
 --> Read() - to read the data from the specified file
https://github.com/open-power/skiboot/blob/master/libflash/file.c#L52

Better to implement the functionality in c++

**Comment by ojayanth** [comment]
https://github.ibm.com/open-power/guard/pull/2
