### ISSUE TITLE
Guard:  API- Guard partition clear

### ISSUE THREAD

**Issue by ojayanth** [ibm-openbmc/dev#1956]
- Clear the rewetted entries in the Guard partition.

**Comment by devenrao** [comment]
1. Block level clear methods to clear guard records from the guard partitoin.
2.1. After a record is cleared all other records in the guard file need to be moved up if the record deleted is not the last one.
2.2. Last guard record need to be cleared.
3. Throw runtime errors so that the caller can catch and create PEL's
4. Do not use phosphor-logging traces as there will be cyclic dependency as the guard manager will be implemented in phosphor-logging , rather use normal std::cerr for any log statements.

Code to refer from skiboot for guard read
block_level_read (https://github.com/open-power/skiboot/blob/master/libflash/blocklevel.c#L103)
Flash File
 --> Read() - to read the data from the specified file
https://github.com/open-power/skiboot/blob/master/libflash/file.c#L52

Better to implement the functionality in c++

**Comment by ojayanth** [comment]
https://github.ibm.com/open-power/guard/pull/2
