### ISSUE TITLE
LED Callouts :: Handle the Fru Repair 

### ISSUE THREAD

**Issue by vishwabmc** [ibm-openbmc/dev#2052]
When the FRU is repaired, the customer is expected to mark ticket as closed. This would mean some field in the PEL to be reset. When that happens, PEL needs to look at what all LEDs to be cleared much in same way it did as part of lighting the LEDs..

Result : Undo action on all LEDs that is conforming to LightPath strategy.

**Comment by spinler** [comment]
For turning off fault LEDs, the LightPath spec just says:
1. Turn off all fault LEDs on a boot
2. Turn of fault LEDs for hotpluggable FRUs like fans and power supplies when they are hotplugged.

For 2, that was being done on Witherspoon by the code setting the Resolved property in the OpenBMC event log.  I'm not sure if we can do that now though because support wasn't keen on users being able to turn off LEDs themselves.

**Comment by vishwabmc** [comment]
> For turning off fault LEDs, the LightPath spec just says:
> 
>     1. Turn off all fault LEDs on a boot

- This is handled in #2115 
> 
>     2. Turn of fault LEDs for hotpluggable FRUs like fans and power supplies when they are hotplugged.
> 
> 

- As seen from the discussions, this should also be covered as part of boot ?

> For 2, that was being done on Witherspoon by the code setting the Resolved property in the OpenBMC event log. I'm not sure if we can do that now though because support wasn't keen on users being able to turn off LEDs themselves and there will be an interface in the web UI to resolve logs.

- May be do what the FSP did

**Comment by spinler** [comment]
@vishwabmc I don't think I have any work here.  I assigned back to you.

**Comment by vishwabmc** [comment]
There is nothing needed of PEL on handling a FRU repair. If a FRU is serviced, the component that is responsible for FRU being repaired will have to tell the LED to turn off.. Closing this.......
