### ISSUE TITLE
Device tree:  Location code  attribute support

### ISSUE THREAD

**Issue by ojayanth** [ibm-openbmc/dev#2131]
Add location code attribute support in device tree and initialize the data based on MRW.

**Comment by RameshIyyar** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Location code Attribute in Device tree](https://trello.com/c/OA42Rbpl/25-location-code-attribute-in-device-tree)

**Comment by RameshIyyar** [comment]
**Design details:**

The "LOCATION_CODE" attribute is used to locate the fru (field replaceable unit) in motherboard and this attribute will have prefix as "Ufcs-" to expand the location code with feature code and serial number of particular fru at runtime (e.g. Ufcs-P0-C15 => U78D8.ND1.ENC9200-P0-C15).

To add this attribute, added platform specific (bmc) perl module to process system mrw xml and add that attribute with value. This new perl module will be called by build option with value as "bmc".

Used new platform specific perl module because, the "processMrw.pl" script producing "STATIC_ABS_LOCATION_CODE" attribute without placeholder "Ufcs-" as prefix to expand the location code i.e with unit feature code and it serial number based on platform (HB, that script forked from HB) interest but, for bmc "LOCATION_CODE" attribute required with that prefix to expand that particular fru location code with actual value at runtime.

Currently, the "LOCATION_CODE" attribute added for below targets. So, it can be extended to any required targets.

- PROC
- DIMM
- OCMB
- BMC

**Patch:**
- [processMrw_bmc: Added LOCATION_CODE](https://github.ibm.com/phal/pdata/pull/34)
