### ISSUE TITLE
Ignore Guard records for newly added  master processor FRUs

### ISSUE THREAD

**Issue by ojayanth** [ibm-openbmc/dev#2195]
For any serial number change in in the master processor  with guard records , phal ipl should ignore the guard records in the sbe config update isteps to core functionla state

**Comment by RameshIyyar** [comment]
@ojayanth @rsnair The flow for this issue is, guard record created for master processor and Field engineer replaced the faulty master processor then attempting booting so, that time we should ignore the guard record of master processor to apply ?

If so, How phal can get to know the processor difference ? serial and part number ? Looks, **libguard** did not add those filed in guard record due to **cec device tree** does not have serial and part number attributes ?

**Comment by ojayanth** [comment]
With new direction , Master Guard record apply should ignore from updatehwmodel. This will help to not to add this support .

**Comment by ojayanth** [comment]
https://github.com/ibm-openbmc/dev/issues/2195 already handled this.
