### ISSUE TITLE
Backend: Support Web-based SSH

### ISSUE THREAD

**Issue by gtmills** [ibm-openbmc/dev#2243]
Some questions if Web-based SSH will be supported via secure websocket or via Web-based SSH client will connect to the BMC’s SSH server via the SSH protocol. 
If it is the 2nd, not sure there is any work here. 
The GUI story is https://github.com/ibm-openbmc/dev/issues/1490

**Comment by joseph-reynolds** [comment]
This issue is to add BMCWeb support for https://en.wikipedia.org/wiki/Web-based_SSH.

Motivation: IBM service representatives need SSH access to the BMC's command line.  However, in some user environments browser/HTTPS access is available but SSH access is not available, so Web-based SSH is a solution.

The access model is:
  1. Network user (root/admin/service) authenticates to BMCWeb as usual.
  2. User navigates to the Web-based SSH page and pokes the "start a session" button (design TBD).
  3. The WebUI goes to a new URL (TBD: POST /ibm/v1/start-management-console) which creates a secure websocket.  One end is given to the web application, and the other end is connected to the WebUI user's login shell.

Specifically, the WebUI parts are outside the scope of this story, and this story is for a new BMCWeb URL which creates the management-console websocket.

A rough sketch of the code to implement the URL is:
 - create websocket;
 - fork();
 - switch user;
 - exec(the user's login shell) // no SSH server is needed

**Comment by joseph-reynolds** [comment]
We discussed this in the 2021-02-17 security working group meeting.  This seems okay to implement, with a few changes:
1. This is not Web-based SSH at all.
2. Can the WebUI front-end be similar to the existing host console?
3. The BMCWeb back-end cannot just fork/exec.  It should call a service that gives it a Unix socket which BMCWeb can then connect to a websocket to give to the WebUI front end.

**Comment by joseph-reynolds** [comment]
This feature is also requested here: https://github.com/openbmc/obmc-console/issues/17

**Comment by amboar** [comment]
> The BMCWeb back-end cannot just fork/exec. It should call a service that gives it a Unix socket which BMCWeb can then connect to a websocket to give to the WebUI front end.

Can you explain why this is necessary?

**Comment by joseph-reynolds** [comment]
> Can you explain why this is necessary?

No.  I understand the BMCWeb maintainers prefer to have as little logic as possible in the BMCWeb server, and have implementations simply invoke D-Bus services whenever possible.  Hence the D-Bus service solution above.  That seems unnecessarily complex to me.  I prefer that BMCWeb directly create a websocket/fork/exec.

**Comment by amboar** [comment]
> > Can you explain why this is necessary?
> 
> No. I understand the BMCWeb maintainers prefer to have as little logic as possible in the BMCWeb server, and have implementations simply invoke D-Bus services whenever possible. Hence the D-Bus service solution above. That seems unnecessarily complex to me. I prefer that BMCWeb directly create a websocket/fork/exec.

Fair enough.

**Comment by joseph-reynolds** [comment]
See related https://redfishforum.com/thread/492/serial-console-redirection-redfish

**Comment by gtmills** [comment]
Downstream only here.

**Comment by gtmills** [comment]
> Do we need to create multiple sessions for multiple users, right?
> If two users try to access shells from different browsers, do we need to create two shells for each?

A shell for each if we can. 
We can have a max, maybe 4, if we are worried about performance.

**Comment by patelabhishek9893** [comment]
Is this ssh terminal need to support iterative commands like a "top"?

because we get limitations with current xtem.js

**Comment by patelabhishek9893** [comment]
This change does not need on upstream
