### ISSUE TITLE
PFP::monitor - Update app & services to run at standby

### ISSUE THREAD

**Issue by msbarth** [ibm-openbmc/dev#2275]
As a performance enhancement, the fan monitor application and associated service(s) should be updated to run at BMC standby to eliminate the need to parse its JSON configuration on each poweron.

**Comment by spinler** [comment]
One fix will be: https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-fan-presence/+/37418/8/monitor/system.cpp#61

**Comment by spinler** [comment]
I also need to do this so it can host a new D-Bus property for 'imminent power off due to fan fails' to use as the  backing for a PLDM sensor for PHYP alerts (well technically it could still host a d-bus property while just running at power on, but having a transient d-bus property isn't desirable to say the least).

**Comment by spinler** [comment]
This is complete.  One of the many commits this took was https://gerrit.openbmc-project.xyz/c/openbmc/openbmc/+/40582.
