### ISSUE TITLE
Everest Power Host Interface - verify PLDM interface

### ISSUE THREAD

**Issue by derekhoward55** [ibm-openbmc/dev#2440]
Verify Everest config ID read from the RI value in the backplane VPD (see issue https://github.com/ibm-openbmc/dev/issues/1233) is available with GetFRURecordTable cmd.  Use pldmtool fru GetFRURecordTable.

Verify alert status and flags (eg 'ThermalFault') implemented via pldm state sensors.  

A new cmd to pass config ID from entity manager mapping of property "IM" under the "com.ibm.ipzvpd.vsys" (names could change) on the "/xyz/openbmc_project/inventory/system" D-Bus object in the inventory (see issue https://github.com/ibm-openbmc/dev/issues/1751)  is not needed.

**Comment by derekhoward55** [comment]
Here is the Everest config ID info.  Note the text doesn't display the "RT"&"RI" keywords, but it doesn't for some other OEM records either:

    [
        {
            "FRU Record Set Identifier": 3,
            "FRU Record Type": "OEM(254)",
            "Number of FRU fields": 2,
            "Encoding Type for FRU fields": "ASCII(1)"
        },
        {
            "FRU Field Type": "2",
            "FRU Field Length": 4,
            "FRU Field Value": "DINF"
        },
        {
            "FRU Field Type": "3",
            "FRU Field Length": 4,
            "FRU Field Value": "0x00 0xc0 0x00 0x32 "
        }
    ],

**Comment by bentyner** [comment]
Verify alert status and flags (eg 'ThermalFault') implemented via pldm state sensors.

* Thermal alert related PLDM sensors:
{                                                                               
    ...
    "sensorID": 27,                                                             
    "entityType": "[Physical] Cooling subsystem",                               
    ...
    "stateSetID[0]": "Thermal Trip(21)",                                        
    "possibleStatesSize[0]": 1,                                                 
    "possibleStates[0]": [                                                      
        "Normal(1)",                                                            
        "Thermal Trip(2)"                                                       
    ]                                                                           
} 
{
    ...                                                                               
    "sensorID": 28,                                                             
    "entityType": "[Physical] External Environment",                            
    "stateSetID[0]": "Health State(1)",                                         
    ...
    "possibleStatesSize[0]": 2,                                                 
    "possibleStates[0]": [                                                      
        "Normal(1)",                                                            
        "Upper Fatal(9)"                                                        
    ]                                                                           
} 
{
    ...                                                                               
    "sensorID": 29,                                                             
    "entityType": "[Physical] External Environment",                            
    ...
    "stateSetID[0]": "Health State(1)",                                         
    "possibleStatesSize[0]": 1,                                                 
    "possibleStates[0]": [                                                      
        "Normal(1)",                                                            
        "Upper Critical(7)"                                                     
    ]                                                                           
}

* steady state (sensor ID 27, 28, 29, see above):
Apr 03 12:14:13 p10bmc cat[3030]: {                                             
Apr 03 12:14:13 p10bmc cat[3030]:     "compositeSensorCount": 1,                
Apr 03 12:14:13 p10bmc cat[3030]:     "sensorOpState[0]": "Sensor Enabled",     
Apr 03 12:14:13 p10bmc cat[3030]:     "presentState[0]": "Sensor Normal",       
Apr 03 12:14:13 p10bmc cat[3030]:     "previousState[0]": "Sensor Unknown",     
Apr 03 12:14:13 p10bmc cat[3030]:     "eventState[0]": "Sensor Normal"         
Apr 03 12:14:13 p10bmc cat[3030]: }                                             
Apr 03 12:14:13 p10bmc cat[3032]: {                                             
Apr 03 12:14:13 p10bmc cat[3032]:     "compositeSensorCount": 1,                
Apr 03 12:14:13 p10bmc cat[3032]:     "sensorOpState[0]": "Sensor Enabled",     
Apr 03 12:14:13 p10bmc cat[3032]:     "presentState[0]": "Sensor Normal",       
Apr 03 12:14:13 p10bmc cat[3032]:     "previousState[0]": "Sensor Unknown",     
Apr 03 12:14:13 p10bmc cat[3032]:     "eventState[0]": "Sensor Normal"          
Apr 03 12:14:13 p10bmc cat[3032]: }                                             
Apr 03 12:14:13 p10bmc cat[3034]: {                                             
Apr 03 12:14:13 p10bmc cat[3034]:     "compositeSensorCount": 1,                
Apr 03 12:14:13 p10bmc cat[3034]:     "sensorOpState[0]": "Sensor Enabled",     
Apr 03 12:14:13 p10bmc cat[3034]:     "presentState[0]": "Sensor Normal",       
Apr 03 12:14:13 p10bmc cat[3034]:     "previousState[0]": "Sensor Unknown",     
Apr 03 12:14:13 p10bmc cat[3034]:     "eventState[0]": "Sensor Normal"          
Apr 03 12:14:13 p10bmc cat[3034]: }

* warning threshold crossed:
Apr 03 13:48:26 p10bmc cat[3509]: {                                             
Apr 03 13:48:26 p10bmc cat[3509]:     "compositeSensorCount": 1,                
Apr 03 13:48:26 p10bmc cat[3509]:     "sensorOpState[0]": "Sensor Enabled",     
Apr 03 13:48:26 p10bmc cat[3509]:     "presentState[0]": "Sensor Normal",       
Apr 03 13:48:26 p10bmc cat[3509]:     "previousState[0]": "Sensor Unknown",     
Apr 03 13:48:26 p10bmc cat[3509]:     "eventState[0]": "Sensor Normal"          
Apr 03 13:48:26 p10bmc cat[3509]: }                                             
Apr 03 13:48:26 p10bmc cat[3511]: {                                             
Apr 03 13:48:26 p10bmc cat[3511]:     "compositeSensorCount": 1,                
Apr 03 13:48:26 p10bmc cat[3511]:     "sensorOpState[0]": "Sensor Enabled",     
Apr 03 13:48:26 p10bmc cat[3511]:     "presentState[0]": "Sensor Normal",       
Apr 03 13:48:26 p10bmc cat[3511]:     "previousState[0]": "Sensor Unknown",     
Apr 03 13:48:26 p10bmc cat[3511]:     "eventState[0]": "Sensor Normal"          
Apr 03 13:48:26 p10bmc cat[3511]: }                                             
Apr 03 13:48:26 p10bmc cat[3513]: {                                             
Apr 03 13:48:26 p10bmc cat[3513]:     "compositeSensorCount": 1,                
Apr 03 13:48:26 p10bmc cat[3513]:     "sensorOpState[0]": "Sensor Enabled",     
Apr 03 13:48:26 p10bmc cat[3513]:     "presentState[0]": "Sensor Normal",       
Apr 03 13:48:26 p10bmc cat[3513]:     "previousState[0]": "Sensor Unknown",     
Apr 03 13:48:26 p10bmc cat[3513]:     "eventState[0]": "Sensor Lower Fatal"  <--- change
Apr 03 13:48:26 p10bmc cat[3513]: 
} 
- Apr 03 13:22:56 p10bmc virtual-sensor[534]: ASSERT: sensor Ambient_Virtual_Temp is above the upper threshold Warning.
- Apr 03 13:22:56 p10bmc virtual-sensor[534]: ASSERT: sensor Ambient_Virtual_Temp is above the upper threshold SoftShutdown.
- Apr 03 13:22:56 p10bmc sensor-monitor[536]: Threshold Event /xyz/openbmc_project/sensors/temperature/Ambient_Virtual_Temp WarningAlarmHigh = true (sensor value 50)
- Apr 03 13:22:56 p10bmc sensor-monitor[536]: Starting 900000ms SoftShutdownAlarmHigh shutdown timer due to sensor /xyz/openbmc_project/sensors/temperature/Ambient_Virtual_Temp value 50

*  critical threshold crossed:Apr 03 13:55:02 p10bmc cat[3803]: {                                             
Apr 03 13:55:02 p10bmc cat[3803]:     "compositeSensorCount": 1,                
Apr 03 13:55:02 p10bmc cat[3803]:     "sensorOpState[0]": "Sensor Enabled",     
Apr 03 13:55:02 p10bmc cat[3803]:     "presentState[0]": "Sensor Normal",       
Apr 03 13:55:02 p10bmc cat[3803]:     "previousState[0]": "Sensor Unknown",     
Apr 03 13:55:02 p10bmc cat[3803]:     "eventState[0]": "Sensor Normal"          
Apr 03 13:55:02 p10bmc cat[3803]: }                                             
Apr 03 13:55:02 p10bmc cat[3805]: {                                             
Apr 03 13:55:02 p10bmc cat[3805]:     "compositeSensorCount": 1,                
Apr 03 13:55:02 p10bmc cat[3805]:     "sensorOpState[0]": "Sensor Enabled",     
Apr 03 13:55:02 p10bmc cat[3805]:     "presentState[0]": "Sensor Normal",       
Apr 03 13:55:02 p10bmc cat[3805]:     "previousState[0]": "Sensor Unknown",     
Apr 03 13:55:02 p10bmc cat[3805]:     "eventState[0]": "Sensor Upper Critical" <--- change  
Apr 03 13:55:02 p10bmc cat[3805]: }                                             
Apr 03 13:55:02 p10bmc cat[3807]: {                                             
Apr 03 13:55:02 p10bmc cat[3807]:     "compositeSensorCount": 1,                
Apr 03 13:55:02 p10bmc cat[3807]:     "sensorOpState[0]": "Sensor Enabled",     
Apr 03 13:55:02 p10bmc cat[3807]:     "presentState[0]": "Sensor Normal",       
Apr 03 13:55:02 p10bmc cat[3807]:     "previousState[0]": "Sensor Unknown",     
Apr 03 13:55:02 p10bmc cat[3807]:     "eventState[0]": "Sensor Lower Fatal"     
Apr 03 13:55:02 p10bmc cat[3807]: 
} 
- Apr 03 13:55:02 p10bmc virtual-sensor[534]: ASSERT: sensor Ambient_Virtual_Temp is above the upper threshold HardShutdown.
- Apr 03 13:55:02 p10bmc sensor-monitor[536]: Starting 23000ms HardShutdownAlarmHigh shutdown timer due to sensor /xyz/openbmc_project/sensors/temperature/Ambient_Virtual_Temp value 53

* hardshutdown reached
Apr 03 14:01:20 p10bmc sensor-monitor[536]: The HardShutdownAlarmHigh shutdown timer expired for sensor /xyz/openbmc_project/sensors/temperature/Ambient_Virtual_Temp, shutting down

Note: I never see any change in ThermalTrip sensor (ID = 27) - may be hard to capture, fan only or deprecated (?). I note this only because this corresponds to the "ThermalFault" sensor as described in this defect and the workbook.

**Comment by bentyner** [comment]
Defect status:
- Done: Verify Everest config ID read from the RI value in the backplane VPD (see issue https://github.com/ibm openbmc/dev/issues/1233) is available with GetFRURecordTable cmd. Use pldmtool fru GetFRURecordTable.
- Done: Verify alert status and flags (eg 'ThermalFault') implemented via pldm state sensors.
- NA: A new cmd to pass config ID from entity manager mapping of property "IM" under the "com.ibm.ipzvpd.vsys" (names could change) on the "/xyz/openbmc_project/inventory/system" D-Bus object in the inventory (see issue https://github.com/ibm-openbmc/dev/issues/1751) is not needed.

**Comment by derekhoward55** [comment]
Re: Thermal Trip - seems to just be hard to capture.  Will be changed after service mode times out after fans are removed, but when phyp subsequently shuts down, the thermal fault dbus property will be cleared by bmc resulting in the sensor being set back to '1' again.

Matt verified PHYP shut down when pulling multiple fans, and thermaltrip would be the only applicable sensor updated for PHYP to act upon, so will close this.
