### ISSUE TITLE
Enhance fan tracing support - add device access info

### ISSUE THREAD

**Issue by derekhoward55** [ibm-openbmc/dev#2464]
From: Bradley W Bishop/Rochester/IBM
Subject: Interlock with Australia team - OpenBMC/SP-Next Discussion
Date: Mon, Jun 1, 2020 3:41 PM

Hi all
I had a todo from the 5/13 call to start to formalize the OpenBMC logging best practices and then identify some work we could do to implement those - the immediate goal being to make debugging problems faster when we do P10 bringup.

I think this will be an iterative process - the one I've heard the most feedback on is that journal -o verbose is required to debug and slows things down, so I started with that and put something out on the project mailing list here:

https://lists.ozlabs.org/pipermail/openbmc/2020-June/021899.html

If you could have a look and weigh in that would be appreciated. Also if you have any thoughts on what the next anti-pattern to fix should be please reply here or to my post on the mailing list, and I'll push that along.

To get started I propose we audit these repositories for interactions with the kernel:

phosphor-hwmon
ibm-vpd-parser/openpower-vpd-parser
phosphor-power

and ensure that anywhere we are doing fileops on i2c devices we add the filename, system call and errno to the MESSAGE field.

To do this, we should implement a phosphor::logging::log wrapper that enables a MESSAGE field format string (right now it only works with a fixed string).

thx - brad

**Comment by msbarth** [comment]
From the description given above, there are no locations within the fan applications that do any fileops on i2c devices. The fan applications strictly rely on phosphor-hwmon for interactions to the fan controller for each fan sensor. The only direct fileops made are within the fan presence application to the fan presence gpios. My proposal under this issue for enhancing the fan tracing would be to use `fmt::format` in the journal tracing done where fan presence is updating a fan's present state and where fan monitoring is updating a fan's functional state. Fan control has no critical journal logging that I can think of at the moment since it primarily using phosphor-hwmon to set the target speed of a fan after its calculated what that target should be.

Another fan related application that could be enhanced to use `fmt::format` would be the cooling type application. It currently reads a gpio to update the cooling type of a machine (witherspoon was either air cooled or water cooled based on a jumper setting). So this application should also likely be updated to reflect anything that is added to the journal for a failed access to the gpio its configured to use.

- [ ] At a minimum, include which fan has its presence state updated(presence)
- [ ] At a minimum, include which fan has its functional state updated(monitor)
- [ ] Update journal entry to include failed gpio access information for configured gpio used in determining cooling type(cooling type)

**Comment by msbarth** [comment]
Resolved by https://gerrit.openbmc-project.xyz/37460
