### ISSUE TITLE
Everest - Fan watchdog support

### ISSUE THREAD

**Issue by derekhoward55** [ibm-openbmc/dev#2465]
Update dts and any json config files for 4u fan support (number of fans, rotors/fan, presence info, Watchdog gpio, etc) based on info from system/thermal teams.  Load correct json files using entity manager.

Same fans as Zeppelin, same fan controller as Rainier.  Ensure works as appropriate on simics&hw.

**Comment by derekhoward55** [comment]
Matt, this might be covered already by the stories you opened?

**Comment by msbarth** [comment]
This is partially completed under #2771 and I had opened #2818 for the Everest dts updates needed.
Entity manager updates are being handled by another team and once merged, my fan JSON configs will just be picked up.

I'll need to check on the watchdog config since that was under the `rainier` machine name in the fan recipes, which Everest is also a `rainier` machine under the meta layers, so it should be getting picked up...however I'm not sure if Everest uses the same pins to the max31785 as the Rainier2u/4u's did.

Will use this issue to track any/all fan watchdog related work for Everest.

**Comment by msbarth** [comment]
Found that the GPIOs between Rainier and Everest are the same and can utilize the same configs then to the fan watchdog service. However, did find that the dts files for Rainier and Everest are incorrect in regard to how the fan watchdog pin is driven which at the moment causes these systems' bmc to reboot. Need to update the dts files under this issue and there is no longer the need to handle different GPIOs for these machines, so will push that work out until its needed for another machine.

**Comment by msbarth** [comment]
Everest fan watchdog -> https://github.ibm.com/openbmc/linux/pull/88

**Comment by msbarth** [comment]
Rainier fan watchdog -> https://github.ibm.com/openbmc/linux/pull/89
