### ISSUE TITLE
Redfish code update support for 2 file update; allow switching the system image 

### ISSUE THREAD

**Issue by gtmills** [ibm-openbmc/dev#2485]
Need to support Redfish code update for 2 file upload, this will allow the Vue GUI to support Witherspoon
This includes listing the system images (done), listing the running system image (done) and allowing switching the system image (needs worked, similiar to https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/35226 )

**Comment by gtmills** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/35934
and 
https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/34960 added support for the images 

Still could allow switching of the image via something like 
https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/35226

**Comment by mzipse** [comment]
Work is only applicable to WItherspoon.

**Comment by lxwinspur** [comment]
> Work is only applicable to WItherspoon.

So, could you remove the `ReadyForDev` label? @mzipse @gtmills 
Because we do not have `Witherspoon`.

**Comment by gtmills** [comment]
@lxwinspur Do you have a system that has 2 file code update (bmc and server firmware are separate as below)? 
![2-file-upload](https://user-images.githubusercontent.com/5455127/103695749-654b0b80-4f5a-11eb-8212-0d599eec94f6.JPG)


This is allowing the server firmware to be changed via Redfish. 
Like we do for the BMC but for the server 
```
curl -k  -X PATCH -d \
'{ "Links": { "ActiveSoftwareImage": { "@odata.id":"/redfish/v1/UpdateService/FirmwareInventory/82d3ec86"}}}' \
https://$bmc/redfish/v1/Managers/bmc
```
ActiveSoftwareImage is a PATCHable property on the Bios resource.
This can be tested on any system like a Witherspoon that has 2 file code update (bmc and server firmware are separate)

**Comment by gtmills** [comment]
So the patch should look something like 


curl -k  -X PATCH -d \
'{ "Links": { "ActiveSoftwareImage": { "@odata.id":"/redfish/v1/UpdateService/FirmwareInventory/16814282"}}}' \
https://$bmc/redfish/v1/Systems/system/Bios

**Comment by zhanghaodi** [comment]
@mzipse @gtmills   Now the test has encountered such a problem,when I just uploaded the image,on the web like this 
![图片](https://user-images.githubusercontent.com/53466644/111588103-1218f300-87fe-11eb-8dc7-6cb1a1cfbf51.png)
and through redfish,I got that
```
curl -k -H "X-Auth-Token: $token" -X GET https://${bmc}/redfish/v1/Managers/bmc
{
  "@odata.id": "/redfish/v1/Managers/bmc",
   ...
  "Links": {
    "ActiveSoftwareImage": {
      "@odata.id": "/redfish/v1/UpdateService/FirmwareInventory/a0cae8f5"
    },
    "ManagerForChassis": [
      {
        "@odata.id": "/redfish/v1/Chassis/chassis"
      }
    ],
    "ManagerForChassis@odata.count": 1,
    "ManagerForServers": [
      {
        "@odata.id": "/redfish/v1/Systems/system"
      }
    ],
    "ManagerForServers@odata.count": 1,
    "ManagerInChassis": {
      "@odata.id": "/redfish/v1/Chassis/chassis"
    },
    "SoftwareImages": [
      {
        "@odata.id": "/redfish/v1/UpdateService/FirmwareInventory/3d8e612d"
      },
      {
        "@odata.id": "/redfish/v1/UpdateService/FirmwareInventory/a0cae8f5"
      }
    ],
    "SoftwareImages@odata.count": 2
  },
  ...
}
```
After I set the image to active ,on the web like this
![图片](https://user-images.githubusercontent.com/53466644/111589042-4e008800-87ff-11eb-9b2b-31a2ff65a3eb.png)
and through redfish,I got that
```
{
  "@odata.id": "/redfish/v1/Managers/bmc",
  ...
  "Links": {
    "ManagerForChassis": [
      {
        "@odata.id": "/redfish/v1/Chassis/chassis"
      }
    ],
    "ManagerForChassis@odata.count": 1,
    "ManagerForServers": [
      {
        "@odata.id": "/redfish/v1/Systems/system"
      }
    ],
    "ManagerForServers@odata.count": 1,
    "ManagerInChassis": {
      "@odata.id": "/redfish/v1/Chassis/chassis"
    }
  },
 ...
}
```
At this time, image information cannot be obtained through resfish,but it can be set through PATCH,
```
curl -k -H "X-Auth-Token: $token" -X PATCH -d '{ "Links": { "ActiveSoftwareImage": { "@odata.id":"/redfish/v1/UpdateService/FirmwareInventory/3d8e612d"}}}' https://${bmc}/redfish/v1/Managers/bmc
{
  "@Message.ExtendedInfo": [
    {
      "@odata.type": "#Message.v1_1_1.Message",
      "Message": "Successfully Completed Request",
      "MessageArgs": [],
      "MessageId": "Base.1.8.1.Success",
      "MessageSeverity": "OK",
      "Resolution": "None"
    }
  ]
}
```
And image has taken effect . 
I have some questions about the above test results.
After the image is set to active, the image information cannot be obtained, and the two images cannot be seen on the web at the same time，what are the reasons for this?Maybe it’s because of our machine.
Finally, the PATCH command takes effect. This test result is somewhat different from what you said above. I want to know how to find the reason for this difference.

**Comment by anoo1** [comment]
> After the image is set to active, the image information cannot be obtained, and the two images cannot be seen on the web at the same time，what are the reasons for this?Maybe it’s because of our machine.

Hi, this is likely because the system only supports one image. During the update, the 'old' image (the one currently running on the system), is marked as deleted (all associations are removed) so that the new image takes its place. This has the side effect that until the system is rebooted, it appears as it doesn't have a current image.
There's probably an improvement that can be done, but for now this is expected for systems with one image (that use the static layout).

> Finally, the PATCH command takes effect. This test result is somewhat different from what you said above. I want to know how to find the reason for this difference.

It seems your test was successful, so any difference is because the one-image vs two-image support. I'll check with @gtmills next week but seems to me that all the work has been completed for this story.

**Comment by zhanghaodi** [comment]
@mzipse @anoo1 Has the result of the discussion come out, can you share it here?
Is there anything else I can help?

**Comment by zhanghaodi** [comment]
@mzipse @anoo1 @gtmills 
What is the result of the discussion?
Has the problem been solved?
If the problem is solved, can this issue be blocked?
If not resolved, please indicate the direction.

**Comment by gtmills** [comment]
>  Has the problem been solved?

This is still a problem. If you have a system with 2 host images, you can not switch between them. 
https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/35226 added this for BMC but we don't have anything for the host image to do this.

**Comment by zhanghaodi** [comment]
@gtmills @mzipse 
Ours is a Dubai machine, we don’t need this feature at present,
But the support ```Witherspoon``` mentioned earlier, do they need this feature.

Could you remove the ```ReadyForDev``` label ?
We don't need this.

**Comment by zhanghaodi** [comment]
And does ```Rainier``` machine need this function?

**Comment by gtmills** [comment]
Rainier does not need this machine.

**Comment by gtmills** [comment]
Closing. This is still needed but I don't see this ever being a priority.
