### ISSUE TITLE
GUI : FED : Progress Bar - IBM Customization Gradient

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#2539]
## Overview
The Bootstrap OOBE for the progress indicator does not meet IBM design standards. We would like to use a more modern animation using a two-color gradient.

**Comment by ben-bacon** [comment]
Similar in execution to https://github.com/ibm-openbmc/dev/issues/2494#issuecomment-671962217

[My recommendation](https://ibm.enterprise.slack.com/files/WFCJ2UW9E/F018SBGAL30/loadinganimation2.mp4) is to pulse between #251561 and #098AAE at a moderate rate on loop until the process finishes. These colors are on either side of the Primary Blue and will hit that color when pulsing to the opposite color. 

There are concerns that the colors might indicate some other intricate feature or feel out of place since the app does not use much color – while valid, do not seem to be a problem for delivering a more polished piece of the UI. This could also be an opportunity to bring more color into the UI with these two colors defined. 

User testing this might be an overreach of validation efforts. It is fairly common practice to use a loading bar with a gradient pulse.

**Comment by ben-bacon** [comment]
Updated the color hexes. They we're the wrong ones, sorry about that!

**Comment by derick-montague** [comment]
@dixsie ^^ - Thanks @ben-bacon

**Comment by dixsie** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/37143
