### ISSUE TITLE
 Redfish: Power

### ISSUE THREAD

**Issue by gtmills** [ibm-openbmc/dev#276]
/redfish/v1/Chassis/{ChassisId}/Power

https://redfish.dmtf.org/schemas/Power.v1_5_1.json

**Comment by gtmills** [comment]
Will include power supplies
From https://redfish.dmtf.org/redfish/mockups/v1/863#
![redfish_powersupplies](https://user-images.githubusercontent.com/5455127/50983186-88a26380-14c4-11e9-98f3-be7fd368c1f3.PNG)

**Comment by gtmills** [comment]
Also need to include `sensors/aggregation/per_30s/ps*_input_power/average` and `sensors/aggregation/per_30s/ps*_input_power/maxium`. Maps to `/redfish/v1/Chassis/chassis/Power/PowerMetric` potentially

**Comment by gtmills** [comment]
Also need `control/power_supply_attributes/attr/DeratingFactor` to
`/redfish/v1/Chassis/chassis/Power/EfficiencyPercent`

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by gtmills** [comment]
Power supplies are currently under 
```
curl -k https://${bmc}/redfish/v1/Chassis/
{
  "@odata.context": "/redfish/v1/$metadata#ChassisCollection.ChassisCollection",
  "@odata.id": "/redfish/v1/Chassis",
  "@odata.type": "#ChassisCollection.ChassisCollection",
  "Members": [
    {
      "@odata.id": "/redfish/v1/Chassis/chassis"
    },
    {
      "@odata.id": "/redfish/v1/Chassis/motherboard"
    },
    {
      "@odata.id": "/redfish/v1/Chassis/powersupply0"
    },
    {
      "@odata.id": "/redfish/v1/Chassis/powersupply1"

```

**Comment by smccarney** [comment]
Ed wants to treat Power Supplies as chassis in Redfish.  It solves some problems for them I believe.  Due to this, they made a change where all the sensors of type "power" are merged into a single Redfish "PowerSupply" object.

This caused strange behavior on Witherspoon when all the power sensors (VRMs and PSUs) were associated with the top level chassis.  They were all merged together into a single Redfish "PowerSupply".

To handle this, we did the following:
* Moved the PSU power sensors to be in an association with the PSU inventory item rather than the top level chassis.  So there is now a mapper association from PSU inventory item -> all sensors for that PSU.
* Removed the other power sensors from the top level chassis association for now.  The bmcweb sensors code will need to be enhanced to handle non-PSU power sensors.

**Comment by gtmills** [comment]
Long term PowerSupplies should move from Chassis to the Power Schema. Ed was okay with this. 

The PowerSupplies in the Power schema have VPD like Model, Serial Number, etc, so not sure we even need the assembly schema for power supplies.

http://redfish.dmtf.org/schemas/v1/Assembly.v1_2_1.json#/definitions/Assembly

Edited the title to say move power supplies

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh
