### ISSUE TITLE
Redfish: Manager (missing properties) 

### ISSUE THREAD

**Issue by gtmills** [ibm-openbmc/dev#281]
https://redfish.dmtf.org/schemas/Manager.v1_5_0.json

/redfish/v1/Managers/{ManagerId}

Already there but need to get properties like Manufacturer, SerialNumber in there. 

```
 curl -k -H "X-Auth-Token: $bmc_token" -X GET https://${bmc}/redfish/v1/Managers/bmc
{
  "@odata.context": "/redfish/v1/$metadata#Manager.Manager",
  "@odata.id": "/redfish/v1/Managers/bmc",
  "@odata.type": "#Manager.v1_3_0.Manager",
  "Actions": {
    "#Manager.Reset": {
      "ResetType@Redfish.AllowableValues": [
        "GracefulRestart"
      ],
      "target": "/redfish/v1/Managers/bmc/Actions/Manager.Reset"
    }
  },
  "DateTime": "2019-01-10T16:57:59+00:00",
  "Description": "Baseboard Management Controller",
  "EthernetInterfaces": {
    "@odata.id": "/redfish/v1/Managers/bmc/EthernetInterfaces"
  },
  "FirmwareVersion": "v2.4-232-gb79d10a-dirty",
  "Id": "bmc",
  "LogServices": {
    "@odata.id": "/redfish/v1/Managers/bmc/LogServices"
  },
  "ManagerType": "BMC",
  "Model": "OpenBmc",
  "Name": "OpenBmc Manager",
  "NetworkProtocol": {
    "@odata.id": "/redfish/v1/Managers/bmc/NetworkProtocol"
  },
  "Oem": {
    "@odata.context": "/redfish/v1/$metadata#OemManager.Oem",
    "@odata.id": "/redfish/v1/Managers/bmc#/Oem",
    "@odata.type": "#OemManager.Oem",
    "OpenBmc": {
      "@odata.context": "/redfish/v1/$metadata#OemManager.OpenBmc",
      "@odata.id": "/redfish/v1/Managers/bmc#/Oem/OpenBmc",
      "@odata.type": "#OemManager.OpenBmc"
    }
  },
  "PowerState": "On",
  "UUID": "5ea3e1a1-6dc8-4ec3-86aa-682cc1936787"

```

```
 curl -c cjar -b cjar -k -H "Content-Type: application/json" -X GET  https://${BMC_IP}/xyzopenbmc_project/inventory/system/chassis/motherboard/boxelder/bmc
{
  "data": {
    "BuildDate": "",
    "FieldReplaceable": false,
    "Manufacturer": "aaaabbbbccccdddd",
    "Model": "",
    "PartNumber": "01DH137         ",
    "Present": true,
    "PrettyName": "BMC PLANAR  ",
    "SerialNumber": "YL10UF78A0H4    ",
    "UUID": ""
  },
  "message": "200 OK",
  "status": "ok"
}
```

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by devenrao** [comment]
The following fields are not present in the schema too, so assume we cannot support unless we define an OEM for it
"BuildDate"
"FieldReplaceable"
"Manufacturer"
"PartNumber"
"PrettyName"
"SerialNumber"

**Comment by rfrandse** [comment]
refresh

**Comment by santoshpuranik** [comment]
I made a list of all Manager properties that are listed in the RF schema as well as those in the Manager object in the inventory. Need to discuss further on which of those needs to be supported for the V1 epic.

RF Property|REST/DBUS Property|Already supported in bmcweb?|Comments
-----------|------------------|----------------------------|--------
Not found|BuidDate|No|Do we need to add OEM?
Not found|FieldReplaceable|No|Do we need to add OEM?
Not found|Manufacturer|No|Do we need to add OEM?
Model|Model|Yes, but hardcoded to “BMC” – TODO|
Not found|Part Number|No|Do we need to add OEM?
Not found|Present|No|Do we need to add OEM?
Name|Pretty Name|Yes, hardcoded to “OpenBMC Manager”|Do we need to change? The name in inventory may not be suitable
Not found|SerialNumber|No|Do we need to add OEM?
UUID|UUID|Yes, bmcweb generates a UUID|Change to use the one in the inventory?
DateTime|??|No|Could reuse some part of  https://github.com/ibm-openbmc/dev/issues/257 /xyz/openbmc_project/time/?
DateTimeLocalOffset|??|No|Could reuse some part of  https://github.com/ibm-openbmc/dev/issues/257 /xyz/openbmc_project/time/?
Status|??|No|State and Health of the Manager.
Description|??|Yes, hardcoded.|
EthernetInterfaces||Yes|
FirmwareVersion|/etc/os-release?|No|
GraphicalConsole|KVM IP info|No|Can be hardcoded?
HostInterfaces|??|No|Bunch of information about the Manager <==> Host interface. Can be hardcoded?
Id|NA|Yes|NA
Links|??||Just contains links to other resources related to this, probably NA for us?
LogServices|||I think this is already being worked.
ManagerType|??|Yes, hardcoded to “BMC”|
NetworkProtocol||Yes|
Oem|??|No|To decide what to put in Oem, if at all.
PowerState|??|Yes, hardcoded to ON|Guess the manager is always powered ON since it is the one responding.
Redundancy|??|No|Not needed just yet?
Redundancy@odata.count||No|Not needed just yet?
RemoteAccountService|NA|No (not in the manager)|Just refer to the AccountService from the manager?
RemoteRedfishServiceUri|NA|No (not in the manager)|Just refer to the AccountService from the manager?
SerialConsole|??|No|Allowed serial consoles over a Serial interface (ex. Telnet, IPMI, etc..)
SerialInterfaces|??|No|List of serial interfaces in the manager. Properties like bitrate, baudrate, etc...
ServiceEntryPointUUID|NA|No|Service Root’s UUID.
VirtualMedia|??|??|This is being worked too, I think.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by gtmills** [comment]
@santoshpuranik For OP940, we said no OEM properties just mapping over the old API to the standard redfish APIs so don't worry about OEMs.

**Comment by santoshpuranik** [comment]
@gtmills : Yes, will be ignoring all OEM for now (while asking the Redfish forum that the missing properties be added to the RF schema).

What other properties in the list I made are a part of the "old API"? Do we have use-cases to support each and every one of them?

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by gtmills** [comment]
I think we should hardcode GraphicalConsole, look at state/bmc0 for the PowerState, and read the model from  `/xyz/openbmc_project/inventory/system/chassis/motherboard/boxelder/bmc`

**Comment by gtmills** [comment]
Could we also hardcode SerialConsole ?

**Comment by gtmills** [comment]
Opened https://github.com/ibm-openbmc/dev/issues/480 to track upstreaming some of these properties

**Comment by santoshpuranik** [comment]
> I think we should hardcode GraphicalConsole, look at state/bmc0 for the PowerState, and read the model from `/xyz/openbmc_project/inventory/system/chassis/motherboard/boxelder/bmc`

Model in the BMC inventory object is empty (checked on a few winterspoons). Is that expected?

**Comment by santoshpuranik** [comment]
> Could we also hardcode SerialConsole ?

OK. Not sure if hardcoding these within BMCWEB is going to be accepted, but I'll try.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by santoshpuranik** [comment]
> > I think we should hardcode GraphicalConsole, look at state/bmc0 for the PowerState, and read the model from `/xyz/openbmc_project/inventory/system/chassis/motherboard/boxelder/bmc`
> 
> Model in the BMC inventory object is empty (checked on a few winterspoons). Is that expected?

Looks like it is. No one seems to be filling in the BMC model.

**Comment by santoshpuranik** [comment]
Resolved by: https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/20025

**Comment by santoshpuranik** [comment]
I have hardcoded the Serial and Graphical connection info. I did not find a way to get the BMC model (the property in inventory object is empty, and there is nothing in the BMC VPD that will tell us it's model).

Alsoi, state/bmc0 does not seem to map to BMC's power state. I believe that should always be ON if we have bmcweb running and able to respond.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/20025 merged

**Comment by ssombar** [comment]
FYI,
GraphicalConsole attribute enablement: https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/21082
