### ISSUE TITLE
Rainier 1s4u support

### ISSUE THREAD

**Issue by derekhoward55** [ibm-openbmc/dev#2986]
Support 1s4u version of system.

Different config data - typically in json files or dts.  No known code changes; data changes only.

New 1000W PS.
Fewer fans.
Fewer vrms.
Same sequencer & pgoods.

**Comment by spinler** [comment]
Since I don't know where else to put this: there are also tables of device path callouts from the MRW, like https://github.ibm.com/openbmc/openbmc/blob/1020/meta-ibm/recipes-phosphor/logging/phosphor-logging/rainier/ibm,rainier-4u_dev_callouts.json.  The 1s could use the same one.  Maybe just copy the file to the new name?

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh
