### ISSUE TITLE
Power Supply Firmware Update

### ISSUE THREAD

**Issue by spinler** [ibm-openbmc/dev#315]
Provide support for firmware update of a PMBus-compliant power supply attached over a PMBus interface to the BMC.

The power supply code image would come from the power supply vendor.  

The BMC would do all that is necessary to prepare the individual ps for the update, download the code to the ps, and reset or re-initialize the ps to be re-integrated into the systems power complex.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by mine260309** [comment]
Some general questions need to be clarified before writing the design document:

1. When host is powered up, is it allowed to do PSU firmware update?
2. In the case that there is only one PSU has power and the others have no AC input:
   * Is it allowed to do PSU firmware update?
   * If yes, is it possible to do PSU firmware update on all the PSUs, or only the PSU that has AC input, or only the PSUs that have no AC input?

**Comment by rfrandse** [comment]
refresh

**Comment by mine260309** [comment]
@derekhoward55 Could you kindly help to answer the above questions?

Some feedback from IPS who had experience on this:
1. If there are redundant PSUs, the host is not required to be off to update PSU firmware;
   Otherwise, the host is required to be off.
2. Different PSU could use different methods (e.g. i2c registers/commands) to update the firmware.

**Comment by derekhoward55** [comment]
Hello, thanks for the help with this, sorry for the delay.  We've been discussing the questions via email with the power supply owners, here are our answers:

1.  We only want the power supply firmware update done when the system is at standby, not when the host is on.  This is to prevent undesirable behavior or even PSU damage that could occur when the PSU is running.

2. Yes the update can be done to a PSU when it doesn't have AC applied, as the PSU will be cross-powered.  We would want to avoid the BMC getting a POR (reset) due to a PSU being updated.  But an individual PSU can be updated whether AC is applied or not.

Please let us know if they have any other questions, thanks!

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by mine260309** [comment]
For this whole epic, most of the tasks are done.
The remaining parts are:
1. The bitbake recipe is not merged yet, due to some concern during the review.
2. The PSU update util is not implemented on Swift (and the task is blocked).

On FP5280G2 machine (meta-inspur/meta-fp5280g2), the whole PSU code update is tested and it runs well. But the recipes are not submitted to gerrit due to the recipe for this service not merged.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by ChicagoDuan** [comment]
Hi all,
     The bitbake recipe is merged.
     It works ok on fp5280g2, and the  fp5280g2's recipes is merged too.
     So I think we can close this task, and we don't need to wait for blocked task: PSU code update: do update on Witherspoon/Swift   #1330
     What's your opinion?  thanks!
      
      https://github.com/openbmc/openbmc/blob/master/meta-phosphor/recipes-phosphor/power/phosphor-psu-software-manager_git.bb

      https://github.com/openbmc/openbmc/blob/master/meta-inspur/meta-fp5280g2/recipes-phosphor/power/phosphor-fp5280g2-psu-update.bb

**Comment by lxwinspur** [comment]
@mzipse 
Could we close this issue?

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by gtmills** [comment]
We still want this but tracked by PFD-91 instead
