### ISSUE TITLE
Dump: SBE dump - Create sbe dump on host watchdog timeout

### ISSUE THREAD

**Issue by geissonator** [ibm-openbmc/dev#3297]
Building upon #2866 , need to check if the host timeout occurred when the SBE was running or if the SBE was running. Based on that, call the correct dump API.

https://github.com/open-power/pdbg/blob/master/libpdbg/libpdbg_sbe.h#L127 has the code to check if the SBE has completed or not. 

Still some discussion with @ojayanth and team on how we call this from the watchdog app.

**Comment by ojayanth** [comment]
Hostboot watchdog also can trigger due to SBE internal boot failure related to hwp failure. In this case SBE stores the HWP failure FFDC information internal buffer enables async FFDC bit enabled to indicate BMC there is is FFDC available. In this case BMC should making additional t chip-op to collect FFDC information instead of making SBE dump.
High level flow:
- Watchdog timeout:
   - Check SBE window or Hostboot boot window
     - SBE boot window.
         - Collect SBE FFDC using captureFFDC(struct pdbg_target *proc) https://github.com/open-power/ipl/blob/main/libphal/phal_sbe.C#L59
         - Check reason for failure , 
                -   if is related to SBE timeout or no FFDC data -- Trigger SBE dump( Primary processor)
                -   else create SBE specific Error log ( Primary processor)
                -   update SBE state to failed  
  Reference code is available             
 - https://gerrit.openbmc-project.xyz/c/openbmc/openpower-proc-control/+/47020
 -  https://gerrit.openbmc-project.xyz/c/openbmc/openpower-proc-control/+/47021/2

**Comment by ojayanth** [comment]
@sbteeks @geissonator
