### ISSUE TITLE
Review downstream bmcweb PR for common practice changes and other general discussion topics

### ISSUE THREAD

**Issue by rfrandse** [ibm-openbmc/dev#3341]
https://github.com/ibm-openbmc/bmcweb/pull/94
https://github.com/ibm-openbmc/bmcweb/pull/97

**Comment by RameshIyyar** [comment]
I will list out the pending comments to address in the mentioned PR

**Comment by RameshIyyar** [comment]
- https://github.com/ibm-openbmc/bmcweb/pull/96: Workaround for DCM
  - https://github.com/ibm-openbmc/bmcweb/pull/96#discussion_r711847847
- https://github.com/ibm-openbmc/bmcweb/pull/76
  - https://github.com/ibm-openbmc/bmcweb/pull/76#discussion_r705862322 - Addressed in the last patch (using different logic)
  - https://github.com/ibm-openbmc/bmcweb/pull/76#discussion_r699433162 
  - https://github.com/ibm-openbmc/bmcweb/pull/76#discussion_r702339631 - Addressed in the last patch
  - https://github.com/ibm-openbmc/bmcweb/pull/76#discussion_r702355498 - Same comment (handle exception for tuple) in many place 
  - Added the HardwareIsolation LogService URI directly instead of checking the backend so, this comment is no more valid

**Comment by sunharis** [comment]
Migrate-Yes

**Comment by rfrandse** [comment]
tracking in jira
