### ISSUE TITLE
GUI: FED: Bug: Unable to delete all dumps and event logs

### ISSUE THREAD

**Issue by dixsie** [ibm-openbmc/dev#3415]
Delete all button on event logs and dumps doesn't work.

## Steps to Reproduce the Problem
1. Find a rainier with multiple dumps or event logs entries
1. Use the upper left check box that selects all entries
1. Choose the delete button

## Expected:
All entries to get deleted

## Actual:
Nothing happens
User has to delete each entry one at a time

Ability to delete one at a time does work.

## Specifications
  - Browser: 
  - Version: 36.4

## Defect
https://w3.rchland.ibm.com/projects/bestquest/?defect=SW541332

**Comment by Nikhil-Ashoka** [comment]
Both Dumps and Event Logs are working as expected in master branch.

**Comment by dixsie** [comment]
@Nikhil-Ashoka can you check out the toast message count, when I deleted 6 dumps it said successfully deleted 1 dump. You may need to look at https://kazupon.github.io/vue-i18n/ for how to use the count in the translation file

**Comment by Nikhil-Ashoka** [comment]
Resolved by: https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/50360

**Comment by Nikhil-Ashoka** [comment]
![image.png](https://images.zenhubusercontent.com/61c40f5ed77a9c0463047832/913a4d69-7233-42af-817d-b7da7ece5b30)

If we give the selected rows directly when the length of the selected rows is less than that of the total capacity. It displays as zero, this problem is solved when the selected rows length is stored in a variable before deleted.
