### ISSUE TITLE
IPMI: dcmi get_conf_parm command is failing

### ISSUE THREAD

**Issue by jayeshmpatel** [ibm-openbmc/dev#3635]
Internal defect: https://jazz07.rchland.ibm.com:13443/jazz/web/projects/CSSD#action=com.ibm.team.workitem.viewWorkItem&id=578377
FVTR 1050:Rainier:IPMI: dcmi get_conf_parm command is failing

## Expected Behavior
dcmi get_conf_parm command should display the config parameter details.

## Actual Behavior
It failed with following:

DCMI request failed because: Unspecified error (ff)
Error Get DCMI Configuration Parameters!

## Steps to Reproduce the Problem
bash-4.2$ ipmitool -I lanplus -C 17 -N 3 -p 623 -U ipmi_admin -H rain57bmc dcmi get_conf_param

## Specifications
  - BMC Version:  fw1050.00-9-1050.2341.20231003a (NL1050_038)

-- Journal traces:
Oct 05 05:28:55 openbmc ipmid[548]: sd_bus_call: xyz.openbmc_project.Common.Error.ResourceNotFound: The resource is not found.
Oct 05 05:28:55 openbmc netipmid[608]: Removing idle IPMI LAN session, id: 264038148, handler: 1
Oct 05 05:29:06 openbmc ipmid[548]: sd_bus_call: xyz.openbmc_project.Common.Error.ResourceNotFound: The resource is not found.
Oct 05 05:29:06 openbmc netipmid[608]: Removing idle IPMI LAN session, id: 622125676, handler: 1

Note: Same issue was tracked previously during May time frame: https://github.com/ibm-openbmc/dev/issues/3624 and was fixed with fw1050.00-2.34.. This may be a regression with the latest BMC level. 

Is this an issue due to any upstream changes for this ipmi commands?

**Comment by lxwinspur** [comment]
Fixed this issue upstream:
https://gerrit.openbmc.org/c/openbmc/phosphor-host-ipmid/+/59655

@jayeshmpatel 
Please synchronize this patch to the IBM repo.

**Comment by lxwinspur** [comment]
@jayeshmpatel  @mzipse 
Is there any progress on this issue?
Will the above patch fix this issue?

**Comment by mzipse** [comment]
We have decided to pull this fix into the FW1050.10 service pack and 1060 as well.

**Comment by anoo1** [comment]
Hi @lxwinspur, the fix wasn't working downstream and after discussions with the network team, turns out that the dhcp path has changed downstream. Instead of being the single `/xyz/openbmc_project/network/dhcp` interface path, now there are multiple network paths that host the SendHostNameEnabled property in the 1050/1060 code:

```
      | |-/xyz/openbmc_project/network/eth0/dhcp4
      | `-/xyz/openbmc_project/network/eth0/dhcp6

        |-/xyz/openbmc_project/network/eth1/dhcp4
        `-/xyz/openbmc_project/network/eth1/dhcp6
```

The commits that made these changes downstream are:
https://github.com/ibm-openbmc/phosphor-networkd/pull/96
https://github.com/ibm-openbmc/bmcweb/pull/700

The changes are still under review upstream:
https://gerrit.openbmc.org/c/openbmc/phosphor-networkd/+/63124
https://gerrit.openbmc.org/c/openbmc/bmcweb/+/63390

Per Sunitha, we'd need to make the changes that were done in bmcweb also in ipmi in order to be able to handle the new dhcp network paths.

Let us know if you'd like to look at making these changes in ipmi (it'd require a downstream change plus also submitting it upstream), or we can try asking the ipmi maintainers, or we can find someone in IBM to make the change.

Thanks.

**Comment by lxwinspur** [comment]
@anoo1 
Give me some time, I'll come in next week and tell you the answer :)

**Comment by lxwinspur** [comment]
@anoo1 
Review by: https://gerrit.openbmc.org/c/openbmc/phosphor-host-ipmid/+/68963

**Comment by anoo1** [comment]
thanks @lxwinspur! , the `dcmi get_conf_param` command works now. I've +1 your gerrit changes. I'll be doing an ipmi PR for 1050 and 1060 with your changes.

Output:
```
	DHCP Discovery method	:
		Management Controller ID String is disabled
		Vendor class identifier DCMI IANA and Vendor class-specific Informationa are enabled
	Initial timeout interval	: 6 seconds
	Server contact timeout interval	: 49158 seconds
	Server contact retry interval	: 49158 seconds
```
