### ISSUE TITLE
GUI: fix sensor table columns 

### ISSUE THREAD

**Issue by gtmills** [ibm-openbmc/dev#376]
## Due Dates
- [x] UX: 02/28/19
- [x] Backend: N/A
- [x] FED: 04/12/19

## Team
**SME**: @gtmills 
**DR**: @nicoleconser 
**UX**: @susantjasinski 
**FED**: @derick-montague  

## Design Issue
---

## Development Issue
---

## Resources
![sensors](https://user-images.githubusercontent.com/5455127/52367495-d8b40d80-2a11-11e9-8bd9-d7bbf4d93a4c.PNG)

**Comment by BeccaBroek** [comment]
There is also an issue on this page with multiple messages appearing when a filter returns no sensors. Will resolve with this issue

<img width="1020" alt="screen shot 2019-02-14 at 4 44 07 pm" src="https://user-images.githubusercontent.com/26717697/52822662-f1f33480-3077-11e9-9324-12b212a69de3.png">

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by susantjasinski** [comment]
Intel / Puli updated this panel to include a column for status. I believe he didn't realize that status already displays in the Status table 1) as an icon in the "Name" column for warning and critical status (no icons displays for good/ok status) and 2) as a color change in the "Current" column.

I believe having a column specific for status is a good idea. However, I recommend placing that column to the left of the Name column (rather than the right where Puli put it), and using icons to show status rather than text -- the icons are commonly used and understood by this user set, and it takes up less screen real estate.

I also recommend allowing the new Status and the Name table columns to be sortable.

![image](https://user-images.githubusercontent.com/42817935/53597302-6db8ab00-3b67-11e9-9c82-3de325a3fc06.png)

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by BeccaBroek** [comment]
Resolved by https://gerrit.openbmc-project.xyz/#/c/openbmc/phosphor-webui/+/19184/

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by derick-montague** [comment]
I thought that this was completed, but possibly that we rolled work back due to redfish @gtmills?

**Comment by gtmills** [comment]
We rolled back the moving the sensor page over to Redfish due to missing the current and power sensors. The https://gerrit.openbmc-project.xyz/#/c/openbmc/phosphor-webui/+/19184/ change was based on it

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by derick-montague** [comment]
@gtmills - Should we plan to handle the layout issues that were handled in the code that was rolled back in a different story?

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by derick-montague** [comment]
@gtmills - When will the redfish changes be ready for us to move this forward?

**Comment by gtmills** [comment]
@antwil Has a change here, https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/22496, which implements sensor collection which should contain the rest of the sensors.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by derick-montague** [comment]
There are two issues here that are being addressed:
1. Moving to redfish
1. The table column alignment issues

I have addressed the alignment issue in https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-webui/+/22939. We will want to abandon https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-webui/+/19184/ since it is outdated and the code has been significantly cleaned up.

**Comment by derick-montague** [comment]
> There is also an issue on this page with multiple messages appearing when a filter returns no sensors, looking strange. Will resolve with this issue
> 
> <img alt="screen shot 2019-02-14 at 4 44 07 pm" width="1020" src="https://user-images.githubusercontent.com/26717697/52822662-f1f33480-3077-11e9-9324-12b212a69de3.png">

I need to test this. I just noticed this and need to make sure we address this also.
