### ISSUE TITLE
BMC command line support for  Hostboot debug frame-work

### ISSUE THREAD

**Issue by ojayanth** [ibm-openbmc/dev#490]
Enable existing ecmd-debug-framework.pl in BMC using pdbg backened.
 Pre-req:
   - PERL support 
   - pdbg package support.

**Comment by rfrandse** [comment]
refresh

**Comment by lkammath** [comment]
Scope of this work now is to

Compile the ecmd pdbg code and make it available in BMC
Run ecmd PDBG aka epdbg do getscom/getmem
Modify the HB debug tools to intake the epdbg to get the HB debug data

Have to port tools under https://github.com/open-power/hostboot/raw/master/src/build/debug/ to BMC

**Comment by ojayanth** [comment]
https://github.com/open-power/ecmd-pdbg supports eCMd version of pdbg. 
Readme provides the steps to get install packages.  you can compile locally and patch in the /tmp  is good for POC work.

**Comment by rfrandse** [comment]
refresh

**Comment by lkammath** [comment]
Currently fsp-memdump.sh and ecmd-debug-framework.pl running natively fine  on witherspoon after enabling perl + epdbg and doing some tweak in the current perl code (Some of 64 bit operation may not work due to BMC being 32 bit HW and Kernel also is 32 bit).. I did not extensively test it but  i can give BMC image and other supported packages if some one wanted to verify in detail so we have that gap fixed :slightly_smiling_face: (edited) 

I have tested fsp-memdump.sh to collect the HB mem dump putting Host to quiesced state and got around 10MB of data

Also have tested following options in ecmd-debug-framework.pl

ecmd-debug-framework.pl --tool=Printk
ecmd-debug-framework.pl --tool=PageMgr --tool-options="debug"
compared output with what cronus gives and they look good. (edited)

**Comment by rfrandse** [comment]
refresh

**Comment by ojayanth** [comment]
Work need to be complete as part of this issue.
- PERL recipe changes support in Master ( Debug package)
- Add support for the Host boot debug tools in Meta-ibm ( debug package).

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by ojayanth** [comment]
Task : "Add support for the Host boot debug tools in Meta-ibm ( debug package)" is not a mandatory requirement now. 
Short term plan: ,HB team can copy all these files to /tmp/ along with hbicore.syms (symbolic link file required from the corresponding build) and run their tools live on a system.
Long term: https://github.com/ibm-openbmc/dev/issues/766

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by lkammath** [comment]
Perl is enabled in the debug tarball (Master branch only) . Following is the commit which got integrated

https://gerrit.openbmc-project.xyz/#/c/openbmc/meta-openpower/+/21648/
https://gerrit.openbmc-project.xyz/#/c/openbmc/openbmc/+/22510/
