### ISSUE TITLE
Power supply control common app

### ISSUE THREAD

**Issue by derekhoward55** [ibm-openbmc/dev#917]
Individual PS D-Bus objects supported. Currently 1 app per PS. Determine if we can stay the same, or if we need one all-encompassing app.

If get pgood fail, it can register for PS callbacks, so pgood app can see that a PS is experiencing a fault and not log the pgood fail. Or it could log the 00AC system reference code (SRC) if any PS is experiencing AC loss (okay if individual PS also log a 15x0 src).

Plan on 1 app for all PS.  Master app for ps monitoring and isolation.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by bjwyman** [comment]
Request for repo: https://lists.ozlabs.org/pipermail/openbmc/2019-July/017162.html

**Comment by bjwyman** [comment]
Repo created today: https://lists.ozlabs.org/pipermail/openbmc/2019-July/017253.html

**Comment by bjwyman** [comment]
Moving back to common repo (plan is to rename later). Initially move to using meson:
https://github.com/openbmc/witherspoon-pfault-analysis/commit/11cb6728f6163c601e26353c7ca66eef3bd47073

https://github.com/openbmc/witherspoon-pfault-analysis/commit/39b370a5107b3c65af8bb07b5893ce71ac5f38fd

https://github.com/openbmc/witherspoon-pfault-analysis/commit/b3853e2d3ac295a961e08927d177b40ddd683914

**Comment by bjwyman** [comment]
"If get pgood fail, it can register for PS callbacks, so pgood app can see that a PS is experiencing a fault and not log the pgood fail." I noted a YAML update for the Rainier power sequencer, which makes me question if this pgood checking callback part is still needed:
https://github.com/openbmc/openbmc/commit/f832eadb0d9a22c671a68fd44c4c554ace5b5ff3

**Comment by bjwyman** [comment]
While reviewing a namespace change after the repository rename, I realized that the old code assumed that we should support power history. That should probably be a configurable option of some sort, since that is basically an OEM command for power supplies built to support IBM systems.

**Comment by mine260309** [comment]
@bjwyman Exactly, now since it's the common `phosphor-power`, I plan to put `Witherspoon` related code into a configuration that could be enabled or disabled at build time.

**Comment by bjwyman** [comment]
Original plan for JSON configuration file was via a command line parameter, thinking it could be passed in via some configuration environment variable (from service file).

New plan is tiered approach:
1. Command line parameter -c or --config.
2. Read from "override" location (`/usr/share/<app>/<file>.json`?).
3. Read from default location (specified in `config.h`? `/etc/<app>/<file>.json`?).
4. Read from some D-Bus property that entity-manager hosts/updates.

**Comment by bradbishop** [comment]
> New plan is tiered approach:
> 
> 	• Command line parameter -c or --config.
> 	• Read from "override" location (/usr/share/<app>/<file>.json?).

this needs to be swapped with the one below.  /etc is writeable configuration from the user (overrides).

> 	• Read from default location (specified in config.h? /etc/<app>/<file>.json?).
> 	• Read from some D-Bus property that entity-manager hosts/updates.

**Comment by bjwyman** [comment]
> New plan is tiered approach: • Command line parameter -c or --config. • Read from "override" location (/usr/share/<app>/<file>.json?).
> this needs to be swapped with the one below. /etc is writeable configuration from the user (overrides).
> […](#)
> • Read from default location (specified in config.h? /etc/<app>/<file>.json?). • Read from some D-Bus property that entity-manager hosts/updates.

Okay, so:
1. Command line parameter -c/--config.
2. Read from override location: /etc/<app>/<file>.json.
3. Read from default location: /usr/share/<app>/<path?>/<file>.json.
4. Read from some D-Bus property that entity-manager updates.

3 & 4 might be somewhat intermixed. Need a method to determine path and/or filename. That is likely to be via D-Bus property that indicates machine type.
@bradbishop ?

**Comment by msbarth** [comment]
@bjwyman 
Here's how I saw things working when it came to what I've done with the fan presence app where each of these look for a specific filename (`config.json`) in the following locations until that file is found:
1.  Read from override location: `/etc/phosphor-fan-presence/presence/config.json`
2.  Read from default location: `/usr/share/phosphor-fan-presence/presence/config.json`
3.  Read from directory location give on dbus:
    * Initially this was expected to be a fully qualified directory location to look for the `config.json` file in, now it sounds like the concept has changed to be a single dbus property will provide only the machine name on dbus. So I'll be altering my design (once this is solidified) to use that machine name off dbus as the subdirectory under the default directory location (i.e. `/usr/share/phosphor-fan-presence/presence/[machine]/config.json`) in which to find the config file(s) to use per fan app.

So when it comes to configuring a machine to use the config from some subdirectory(machine name) given on dbus, one would not install any config file(s) to the default location and instead nest them under each machine name subdirectory that's possible within the single image.

Since many of the fan apps have more than a single file that makes up their configuration, I chose to use this directory style approach. I would assume something similar would work in your case using filenames. Note, I do not accept a command line parameter that provides the config file(s) to use, so that would be a special case you'd have to figure out how to handle if its necessary to keep.

**Comment by bradbishop** [comment]
> On Jan 23, 2020, at 1:47 PM, B. J. Wyman <notifications@github.com> wrote:
> 
> Okay, so:
> 
> 	• Command line parameter -c/--config.

Why do we need this?

> 	• Read from override location: /etc//.json.
> 	• Read from default location: /usr/share//<path?>/.json.
> 	• Read from some D-Bus property that entity-manager updates.
> 3 & 4 might be somewhat intermixed. Need a method to determine path and/or filename. That is likely to be via D-Bus property that indicates machine type.
> @bradbishop ?

I’m not convinced you even need a config file.  What is it you want to put there rather than in the EM configuration?

The only reason Matt and others are using config files like they are is because their applications are already written.  You are writing one from scratch so you don’t have to do it that way.

I’d suggest looking at the Intel power applications in dbus-sensors for examples of how to write applications that consume power supply information from EM config files.  Actually I’d suggest just using those applications in the first place instead of writing them from scratch, but if that doesn’t work they can serve as an example.

**Comment by bradbishop** [comment]
> 	• Read from override location: /etc/phosphor-fan-presence/presence/config.json
> 	• Read from default location: /usr/share/phosphor-fan-presence/presence/config.json
> 	• Read from directory location give on dbus:
> 		• Initially this was expected to be a fully qualified directory location to look for the config.json file in, now it sounds like the concept has changed to be a single dbus property will provide only the machine name on dbus. So I'll be altering my design (once this is solidified) to use that machine name off dbus as the subdirectory under the default directory location (i.e. /usr/share/phosphor-fan-presence/presence/[machine]/config.json) in which to find the config file(s) to use per fan app.

@msbarth - yep sorry about the churn on this but I think the desired direction has stabilized now.  Basically the application flow would be:

1 - read <system-type> off dbus
2 - try to load config for <system-type> from /etc/phosphor-fan-presence/<system-type>/foo.json
3 - fall back to config in /usr/share/phosphor-fan-presence/<system-type>/foo.json

does that match your understanding?

**Comment by msbarth** [comment]
> does that match your understanding?

@bradbishop Yes, for the most part, except the `<system-type>` will not be used when looking in `/etc` since there really should be no need to include it here as this is considered the override/patch location that would no contain a config unlessed patched on the machine directly.
And I planned to have each fan application as a subdir to `phosphor-fan-presence` before post-pending the `<system-type>` (i.e. `/usr/share/phosphor-fan-presence/monitor/monitor.json`, `/usr/share/phosphor-fan-presence/presence/config.json`, etc...) just for clearer organization in my opinion...

**Comment by bradbishop** [comment]
> And I planned to have each fan application as a subdir to phosphor-fan-presence before appending the <system-type> (i.e. /usr/share/phosphor-fan-presence/monitor/monitor.json, /usr/share/phosphor-fan-presence/presence/config.json, etc...) just for clearer organization in my opinion...

sounds good to me!

**Comment by bjwyman** [comment]
> On Jan 23, 2020, at 1:47 PM, B. J. Wyman ***@***.***> wrote: Okay, so: • Command line parameter -c/--config.
> Why do we need this?
> • Read from override location: /etc//.json. • Read from default location: /usr/share//<path?>/.json. • Read from some D-Bus property that entity-manager updates. 3 & 4 might be somewhat intermixed. Need a method to determine path and/or filename. That is likely to be via D-Bus property that indicates machine type. @bradbishop ?
> I’m not convinced you even need a config file. What is it you want to put there rather than in the EM configuration? The only reason Matt and others are using config files like they are is because their applications are already written. You are writing one from scratch so you don’t have to do it that way. I’d suggest looking at the Intel power applications in dbus-sensors for examples of how to write applications that consume power supply information from EM config files. Actually I’d suggest just using those applications in the first place instead of writing them from scratch, but if that doesn’t work they can serve as an example.

The -c/--config command line argument could be optional, it was intended to be that way at first, then change to required, now considering changing back to optional. My thought was that you could temporarily point to a file in say `/tmp`, copy to `/etc` path if temporary check looked good. I guess I could throw that out completely and just rely on the file being in `/etc/phosphor-power-monitor/psu_config.json`.

Second choice would then likely be some default location, right now that sounds like `/usr/share/phosphor-power-monitor/psu_config.json`, but ideally that would be `/usr/share/phsophor-power-monitor/<system-type>/psu_config.json`. However, I don't know that we currently have a way to define they <system-type> values, unless there is some `entity-manager` or D-Bus update I have missed out on being notified about.

Perhaps the power supply configuration information could be on D-Bus, via entity-manager, but that is not there yet, and it was not the direction things were going when I started working on this. I don't think anything in the way I started writing this new application would prevent one from swapping out the JSON parsing with reading from D-Bus. So, I think it could be changed to read properties off of D-Bus at some later time.

**Comment by bjwyman** [comment]
So, I did not quite go with the changes I indicated.

Since we are still trying to get entity-manager to set a system-type, or put properties out on D-Bus, I just have the application pulling from a command line argument (-c/--config) or defaulting to `/etc/phosphor-psu-monitor/psu_config.json`.

A later story (ibm-openbmc/dev#918) can be used to update for the planned entity-manager path for configuration data.

**Comment by bjwyman** [comment]
Resolved-by: https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-power/+/28852

**Comment by bradbishop** [comment]
Having a -c option adds needless complexity for code updates.  I advise against it.

I don't recommend looking in /etc before looking in /usr because of this:

https://lists.ozlabs.org/pipermail/openbmc/2019-November/019388.html

**Comment by bradbishop** [comment]
> Having a -c option adds needless complexity for code updates. I advise against it.
> 
> I don't recommend looking in /etc before looking in /usr because of this:
> 
> https://lists.ozlabs.org/pipermail/openbmc/2019-November/019388.html

I think I get it now.  You are doing this as a stop gap - later you'll switch to something else.  Sounds good @bjwyman!
