### ISSUE TITLE
VRM JSON file definition

### ISSUE THREAD

**Issue by derekhoward55** [ibm-openbmc/dev#922]
Implement VRM JSON file structure.

Replace raw i2c accesses with device driver or pass-through (turnaround times not quick enough for low-level device driver changes [can use our own fork, shouldn't be a concern] or skills we don't have)? Consider:

- Require all registers be implemented in DD?
- Need PMBus compliant i2c address and proprietary "config space" i2c address.
- Cmds to vrm phase i2c addresses and master i2c address.
- Do vrm vendors sell vrms made for IBM to other companies, so other server companies would want to re-use our code?

Direct i2c accesses per discussions with team and mgmt.

**Comment by rfrandse** [comment]
refresh

**Comment by amboar** [comment]
It would be good to discuss the queries you have above with myself and @shenki given we maintain and develop the kernel for IBM's OpenBMC efforts.

**Comment by rfrandse** [comment]
refresh

**Comment by smccarney** [comment]
The focus of this work item has evolved into the following:
* Define the JSON config file format that will drive the BMC application controlling/monitoring VRMs.
* Document the JSON config file format using Markdown files in the phosphor-power repository.

The config file format has been designed with two goals in mind:
* Support direct I2C communication with VRMs as the short term solution.
* Make system extensible so that it can support driver-based communication in the medium or long term.

Note: The design template for this work is located here:  https://github.com/openbmc/docs/blob/master/designs/voltage-regulator-configuration.md

**Comment by smccarney** [comment]
Resolved by https://gerrit.openbmc-project.xyz/25871

**Comment by smccarney** [comment]
Merged.
